const COMMANDS: &[&str] = &[
    "get_agent_definition",
    "get_agent_definitions",
    "get_agent_spec",
    "update_agent_spec",
    "get_preset_info",
    "get_preset_infos",
    "get_preset_spec",
    "update_preset_spec",
    "new_preset",
    "rename_preset",
    "unique_preset_name",
    "add_preset",
    "remove_preset",
    "add_agents_and_connections",
    "start_preset",
    "stop_preset",
    "new_agent_spec",
    "add_agent",
    "remove_agent",
    "add_connection",
    "remove_connection",
    "start_agent",
    "stop_agent",
    "write_board",
    "set_agent_configs",
    "get_global_configs",
    "get_global_configs_map",
    "set_global_configs",
    "set_global_configs_map",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
