[package]
name = "tauri-plugin-modular-agent"
version = "0.13.0"
authors = ["Akira Ishino <akira@lumilab.jp>"]
license = "Apache-2.0 OR MIT"
description = "Tauri plugin for Modular Agent"
edition = "2021"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-modular-agent"

[dependencies]
modular-agent-core = "0.22.0"
im = "15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2.8.5" }
thiserror = "2"

[build-dependencies]
tauri-plugin = { version = "2.4.0", features = ["build"] }

# [patch.crates-io]
# modular-agent-core = { path = "../modular-agent-core/modular-agent-core" }
