[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-get-agent-definition",
    "allow-get-agent-definitions",
    "allow-get-agent-spec",
    "allow-update-agent-spec",
    "allow-get-preset-info",
    "allow-get-preset-infos",
    "allow-get-preset-spec",
    "allow-update-preset-spec",
    "allow-new-preset",
    "allow-rename-preset",
    "allow-unique-preset-name",
    "allow-add-preset",
    "allow-remove-preset",
    "allow-add-agents-and-connections",
    "allow-start-preset",
    "allow-stop-preset",
    "allow-new-agent-spec",
    "allow-add-agent",
    "allow-remove-agent",
    "allow-add-connection",
    "allow-remove-connection",
    "allow-start-agent",
    "allow-stop-agent",
    "allow-write-board",
    "allow-set-agent-configs",
    "allow-get-global-configs",
    "allow-get-global-configs-map",
    "allow-set-global-configs",
    "allow-set-global-configs-map",
]
